//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFBS.WebService.webService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.modelo/", ConfigurationName="webService.MainWS")]
    public interface MainWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.modelo/MainWS/Listar_CursoRequest", ReplyAction="http://ws.modelo/MainWS/Listar_CursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WFBS.WebService.webService.Listar_CursoResponse Listar_Curso(WFBS.WebService.webService.Listar_CursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.modelo/MainWS/Listar_CursoRequest", ReplyAction="http://ws.modelo/MainWS/Listar_CursoResponse")]
        System.Threading.Tasks.Task<WFBS.WebService.webService.Listar_CursoResponse> Listar_CursoAsync(WFBS.WebService.webService.Listar_CursoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.modelo/MainWS/Recuperar_PersonaRequest", ReplyAction="http://ws.modelo/MainWS/Recuperar_PersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WFBS.WebService.webService.Recuperar_PersonaResponse Recuperar_Persona(WFBS.WebService.webService.Recuperar_PersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.modelo/MainWS/Recuperar_PersonaRequest", ReplyAction="http://ws.modelo/MainWS/Recuperar_PersonaResponse")]
        System.Threading.Tasks.Task<WFBS.WebService.webService.Recuperar_PersonaResponse> Recuperar_PersonaAsync(WFBS.WebService.webService.Recuperar_PersonaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.modelo/")]
    public partial class clCurso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private string institucionField;
        
        private string nombreField;
        
        private string siglasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string institucion {
            get {
                return this.institucionField;
            }
            set {
                this.institucionField = value;
                this.RaisePropertyChanged("institucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string siglas {
            get {
                return this.siglasField;
            }
            set {
                this.siglasField = value;
                this.RaisePropertyChanged("siglas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.modelo/")]
    public partial class clPersona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string correoField;
        
        private string dvField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private string nombreField;
        
        private string runField;
        
        private string sexoField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dv {
            get {
                return this.dvField;
            }
            set {
                this.dvField = value;
                this.RaisePropertyChanged("dv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string run {
            get {
                return this.runField;
            }
            set {
                this.runField = value;
                this.RaisePropertyChanged("run");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar_Curso", WrapperNamespace="http://ws.modelo/", IsWrapped=true)]
    public partial class Listar_CursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.modelo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string p_run;
        
        public Listar_CursoRequest() {
        }
        
        public Listar_CursoRequest(string p_run) {
            this.p_run = p_run;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar_CursoResponse", WrapperNamespace="http://ws.modelo/", IsWrapped=true)]
    public partial class Listar_CursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.modelo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WFBS.WebService.webService.clCurso[] @return;
        
        public Listar_CursoResponse() {
        }
        
        public Listar_CursoResponse(WFBS.WebService.webService.clCurso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Recuperar_Persona", WrapperNamespace="http://ws.modelo/", IsWrapped=true)]
    public partial class Recuperar_PersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.modelo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string p_run;
        
        public Recuperar_PersonaRequest() {
        }
        
        public Recuperar_PersonaRequest(string p_run) {
            this.p_run = p_run;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Recuperar_PersonaResponse", WrapperNamespace="http://ws.modelo/", IsWrapped=true)]
    public partial class Recuperar_PersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.modelo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WFBS.WebService.webService.clPersona @return;
        
        public Recuperar_PersonaResponse() {
        }
        
        public Recuperar_PersonaResponse(WFBS.WebService.webService.clPersona @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainWSChannel : WFBS.WebService.webService.MainWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainWSClient : System.ServiceModel.ClientBase<WFBS.WebService.webService.MainWS>, WFBS.WebService.webService.MainWS {
        
        public MainWSClient() {
        }
        
        public MainWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFBS.WebService.webService.Listar_CursoResponse WFBS.WebService.webService.MainWS.Listar_Curso(WFBS.WebService.webService.Listar_CursoRequest request) {
            return base.Channel.Listar_Curso(request);
        }
        
        public WFBS.WebService.webService.clCurso[] Listar_Curso(string p_run) {
            WFBS.WebService.webService.Listar_CursoRequest inValue = new WFBS.WebService.webService.Listar_CursoRequest();
            inValue.p_run = p_run;
            WFBS.WebService.webService.Listar_CursoResponse retVal = ((WFBS.WebService.webService.MainWS)(this)).Listar_Curso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFBS.WebService.webService.Listar_CursoResponse> WFBS.WebService.webService.MainWS.Listar_CursoAsync(WFBS.WebService.webService.Listar_CursoRequest request) {
            return base.Channel.Listar_CursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFBS.WebService.webService.Listar_CursoResponse> Listar_CursoAsync(string p_run) {
            WFBS.WebService.webService.Listar_CursoRequest inValue = new WFBS.WebService.webService.Listar_CursoRequest();
            inValue.p_run = p_run;
            return ((WFBS.WebService.webService.MainWS)(this)).Listar_CursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFBS.WebService.webService.Recuperar_PersonaResponse WFBS.WebService.webService.MainWS.Recuperar_Persona(WFBS.WebService.webService.Recuperar_PersonaRequest request) {
            return base.Channel.Recuperar_Persona(request);
        }
        
        public WFBS.WebService.webService.clPersona Recuperar_Persona(string p_run) {
            WFBS.WebService.webService.Recuperar_PersonaRequest inValue = new WFBS.WebService.webService.Recuperar_PersonaRequest();
            inValue.p_run = p_run;
            WFBS.WebService.webService.Recuperar_PersonaResponse retVal = ((WFBS.WebService.webService.MainWS)(this)).Recuperar_Persona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFBS.WebService.webService.Recuperar_PersonaResponse> WFBS.WebService.webService.MainWS.Recuperar_PersonaAsync(WFBS.WebService.webService.Recuperar_PersonaRequest request) {
            return base.Channel.Recuperar_PersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFBS.WebService.webService.Recuperar_PersonaResponse> Recuperar_PersonaAsync(string p_run) {
            WFBS.WebService.webService.Recuperar_PersonaRequest inValue = new WFBS.WebService.webService.Recuperar_PersonaRequest();
            inValue.p_run = p_run;
            return ((WFBS.WebService.webService.MainWS)(this)).Recuperar_PersonaAsync(inValue);
        }
    }
}
